import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;


public class MainAppli {


    public static void main(String[] args) {
        	System.out.println("Démarrage de l'application...");
try {

        Class.forName("org.hsqldb.jdbc.JDBCDriver");
        System.out.println("Driver chargé avec succès!");

} catch (ClassNotFoundException e) {
	System.out.println("Driver pas trouvé");
}

try {

        Connection connection = DriverManager.getConnection("jdbc:hsqldb:file:CLIENTS_BDD","BENOIT","");
        System.out.println("Connexion à la base de données réussie!");

	
        try {
	Statement statement = connection.createStatement();  
                           String createTableSQL = "CREATE TABLE IF NOT EXISTS personnes ("
                        + "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "nom VARCHAR(30) NOT NULL, "
                        + "age INTEGER DEFAULT 0 NOT NULL, "
                        + "adresse VARCHAR(50))"; // Chaîne fermée ici correctement
                statement.execute(createTableSQL);
            System.out.println("Table créée");
        }catch (SQLException e) {
	System.out.println("table pas réussi à créer ");
	}



try {
String insertSQL = "INSERT INTO personnes (nom, age, adresse) VALUES "
                 + "('Alice', 30, '123 Rue A'), "
                 + "('Bob', 25, '456 Rue B')";
Statement statement = connection.createStatement(); 
    int rowsAffected = statement.executeUpdate(insertSQL);
    System.out.println(" lignes insérées.");
} catch (SQLException e) {
    System.out.println("Erreur lors de l'insertion des données : " + e.getMessage());
}



	String selectSQL = "SELECT * FROM personnes";
	try {
System.out.println("on essaie de chercher des données");
	Statement statement = connection.createStatement();
 	   ResultSet resultSet = statement.executeQuery(selectSQL);
  	  while (resultSet.next()) {
   	     int id = resultSet.getInt("id");
    	    String nom = resultSet.getString("nom");
    	    int age = resultSet.getInt("age");
    	    String adresse = resultSet.getString("adresse");
	
        System.out.println("ID: " + id + ", Nom: " + nom + ", Age: " + age + ", Adresse: " + adresse);
    }
} catch (SQLException e) {
    System.out.println("Erreur lors de la sélection des données : " + e.getMessage());
}




} catch (SQLException e) {
	System.out.println("Base pas bon");
}




}
    
}
